//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.obslugaprzelewow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statusZlecenia" type="{http://Main/ServicesSpecification/}StatusZleceniaPrzelewu"/>
 *         &lt;element name="zleceniePrzelewuKrajowego" type="{http://Main/ServicesSpecification/}ZleceniePrzelewuKrajowego"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statusZlecenia",
    "zleceniePrzelewuKrajowego"
})
@XmlRootElement(name = "inicjujZleceniePrzelewuKrajowego", namespace = "http://Main/ServicesIdentification/ObslugaPrzelewow/")
public class InicjujZleceniePrzelewuKrajowego {

    @XmlElement(required = true)
    protected StatusZleceniaPrzelewu statusZlecenia;
    @XmlElement(required = true)
    protected ZleceniePrzelewuKrajowego zleceniePrzelewuKrajowego;

    /**
     * Gets the value of the statusZlecenia property.
     * 
     * @return
     *     possible object is
     *     {@link StatusZleceniaPrzelewu }
     *     
     */
    public StatusZleceniaPrzelewu getStatusZlecenia() {
        return statusZlecenia;
    }

    /**
     * Sets the value of the statusZlecenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusZleceniaPrzelewu }
     *     
     */
    public void setStatusZlecenia(StatusZleceniaPrzelewu value) {
        this.statusZlecenia = value;
    }

    /**
     * Gets the value of the zleceniePrzelewuKrajowego property.
     * 
     * @return
     *     possible object is
     *     {@link ZleceniePrzelewuKrajowego }
     *     
     */
    public ZleceniePrzelewuKrajowego getZleceniePrzelewuKrajowego() {
        return zleceniePrzelewuKrajowego;
    }

    /**
     * Sets the value of the zleceniePrzelewuKrajowego property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZleceniePrzelewuKrajowego }
     *     
     */
    public void setZleceniePrzelewuKrajowego(ZleceniePrzelewuKrajowego value) {
        this.zleceniePrzelewuKrajowego = value;
    }

}
