//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.operacjebankowe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://Main/ServicesSpecification/}StatusZleceniaPrzelewu"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status"
})
@XmlRootElement(name = "inicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego", namespace = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/")
public class InicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego {

    @XmlElement(required = true)
    protected StatusZleceniaPrzelewu status;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusZleceniaPrzelewu }
     *     
     */
    public StatusZleceniaPrzelewu getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusZleceniaPrzelewu }
     *     
     */
    public void setStatus(StatusZleceniaPrzelewu value) {
        this.status = value;
    }

}
