//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.operacjebankowe;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pw.ee.mgr.ebanking.operacjebankowe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pw.ee.mgr.ebanking.operacjebankowe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InicjujPrzewalutowywaniePrzelewuMiedzynarodowego }
     * 
     */
    public InicjujPrzewalutowywaniePrzelewuMiedzynarodowego createInicjujPrzewalutowywaniePrzelewuMiedzynarodowego() {
        return new InicjujPrzewalutowywaniePrzelewuMiedzynarodowego();
    }

    /**
     * Create an instance of {@link ZleceniePrzelewuMiedzynarodowego }
     * 
     */
    public ZleceniePrzelewuMiedzynarodowego createZleceniePrzelewuMiedzynarodowego() {
        return new ZleceniePrzelewuMiedzynarodowego();
    }

    /**
     * Create an instance of {@link InicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego }
     * 
     */
    public InicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego createInicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego() {
        return new InicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego();
    }

    /**
     * Create an instance of {@link StatusZleceniaPrzelewu }
     * 
     */
    public StatusZleceniaPrzelewu createStatusZleceniaPrzelewu() {
        return new StatusZleceniaPrzelewu();
    }

    /**
     * Create an instance of {@link WyplacPieniadzeZKonta }
     * 
     */
    public WyplacPieniadzeZKonta createWyplacPieniadzeZKonta() {
        return new WyplacPieniadzeZKonta();
    }

    /**
     * Create an instance of {@link WplacPieniadzeNaKonto }
     * 
     */
    public WplacPieniadzeNaKonto createWplacPieniadzeNaKonto() {
        return new WplacPieniadzeNaKonto();
    }

    /**
     * Create an instance of {@link InicjujWykonaniePrzelewu }
     * 
     */
    public InicjujWykonaniePrzelewu createInicjujWykonaniePrzelewu() {
        return new InicjujWykonaniePrzelewu();
    }

}
