//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.obslugaprzelewow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="powodzenie" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "powodzenie"
})
@XmlRootElement(name = "notyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowegoResponse", namespace = "http://Main/ServicesIdentification/ObslugaPrzelewow/")
public class NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowegoResponse {

    protected boolean powodzenie;

    /**
     * Gets the value of the powodzenie property.
     * 
     */
    public boolean isPowodzenie() {
        return powodzenie;
    }

    /**
     * Sets the value of the powodzenie property.
     * 
     */
    public void setPowodzenie(boolean value) {
        this.powodzenie = value;
    }

}
