//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.obslugaprzelewow;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pw.ee.mgr.ebanking.obslugaprzelewow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pw.ee.mgr.ebanking.obslugaprzelewow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowegoResponse }
     * 
     */
    public NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowegoResponse createNotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowegoResponse() {
        return new NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowegoResponse();
    }

    /**
     * Create an instance of {@link InicjujZleceniePrzelewuKrajowego }
     * 
     */
    public InicjujZleceniePrzelewuKrajowego createInicjujZleceniePrzelewuKrajowego() {
        return new InicjujZleceniePrzelewuKrajowego();
    }

    /**
     * Create an instance of {@link StatusZleceniaPrzelewu }
     * 
     */
    public StatusZleceniaPrzelewu createStatusZleceniaPrzelewu() {
        return new StatusZleceniaPrzelewu();
    }

    /**
     * Create an instance of {@link ZleceniePrzelewuKrajowego }
     * 
     */
    public ZleceniePrzelewuKrajowego createZleceniePrzelewuKrajowego() {
        return new ZleceniePrzelewuKrajowego();
    }

    /**
     * Create an instance of {@link NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowego }
     * 
     */
    public NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowego createNotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowego() {
        return new NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowego();
    }

    /**
     * Create an instance of {@link InicjujZleceniePrzelewuMiedzynarodowego }
     * 
     */
    public InicjujZleceniePrzelewuMiedzynarodowego createInicjujZleceniePrzelewuMiedzynarodowego() {
        return new InicjujZleceniePrzelewuMiedzynarodowego();
    }

    /**
     * Create an instance of {@link ZleceniePrzelewuMiedzynarodowego }
     * 
     */
    public ZleceniePrzelewuMiedzynarodowego createZleceniePrzelewuMiedzynarodowego() {
        return new ZleceniePrzelewuMiedzynarodowego();
    }

}
