//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.obslugaprzelewow;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ObslugaPrzelewow", targetNamespace = "http://Main/ServicesIdentification/ObslugaPrzelewow/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ObslugaPrzelewow {


    /**
     * 
     * @param statusZlecenia
     * @param zleceniePrzelewuKrajowego
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ObslugaPrzelewow/inicjujZleceniePrzelewuKrajowego")
    @Oneway
    @RequestWrapper(localName = "inicjujZleceniePrzelewuKrajowego", targetNamespace = "http://Main/ServicesIdentification/ObslugaPrzelewow/", className = "pw.ee.mgr.ebanking.obslugaprzelewow.InicjujZleceniePrzelewuKrajowego")
    public void inicjujZleceniePrzelewuKrajowego(
        @WebParam(name = "statusZlecenia", targetNamespace = "")
        StatusZleceniaPrzelewu statusZlecenia,
        @WebParam(name = "zleceniePrzelewuKrajowego", targetNamespace = "")
        ZleceniePrzelewuKrajowego zleceniePrzelewuKrajowego);

    /**
     * 
     * @param statusZlecenia
     * @param zlecenie
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ObslugaPrzelewow/inicjujZleceniePrzelewuMiedzynarodowego")
    @Oneway
    @RequestWrapper(localName = "inicjujZleceniePrzelewuMiedzynarodowego", targetNamespace = "http://Main/ServicesIdentification/ObslugaPrzelewow/", className = "pw.ee.mgr.ebanking.obslugaprzelewow.InicjujZleceniePrzelewuMiedzynarodowego")
    public void inicjujZleceniePrzelewuMiedzynarodowego(
        @WebParam(name = "zlecenie", targetNamespace = "")
        ZleceniePrzelewuMiedzynarodowego zlecenie,
        @WebParam(name = "statusZlecenia", targetNamespace = "")
        StatusZleceniaPrzelewu statusZlecenia);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ObslugaPrzelewow/notyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowego")
    @WebResult(name = "powodzenie", targetNamespace = "")
    @RequestWrapper(localName = "notyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowego", targetNamespace = "http://Main/ServicesIdentification/ObslugaPrzelewow/", className = "pw.ee.mgr.ebanking.obslugaprzelewow.NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowego")
    @ResponseWrapper(localName = "notyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowegoResponse", targetNamespace = "http://Main/ServicesIdentification/ObslugaPrzelewow/", className = "pw.ee.mgr.ebanking.obslugaprzelewow.NotyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowegoResponse")
    public boolean notyfikacjaOZakonczeniuProcesowaniaPrzelewuMiedzynarodowego();

}
