//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.operacjebankowe;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

@WebService(name = "ZarzadzanieOperacjamiBankowymi", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZarzadzanieOperacjamiBankowymi {


    /**
     * 
     * @param zlecenie
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/inicjujPrzewalutowywaniePrzelewuMiedzynarodowego")
    @Oneway
    @RequestWrapper(localName = "inicjujPrzewalutowywaniePrzelewuMiedzynarodowego", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/", className = "pw.ee.mgr.ebanking.operacjebankowe.InicjujPrzewalutowywaniePrzelewuMiedzynarodowego")
    public void inicjujPrzewalutowywaniePrzelewuMiedzynarodowego(
        @WebParam(name = "zlecenie", targetNamespace = "")
        ZleceniePrzelewuMiedzynarodowego zlecenie);

    /**
     * 
     * @param statusZlecenia
     * @param zlecenie
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/inicjujWykonaniePrzelewu")
    @Oneway
    @RequestWrapper(localName = "inicjujWykonaniePrzelewu", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/", className = "pw.ee.mgr.ebanking.operacjebankowe.InicjujWykonaniePrzelewu")
    public void inicjujWykonaniePrzelewu(
        @WebParam(name = "statusZlecenia", targetNamespace = "")
        StatusZleceniaPrzelewu statusZlecenia,
        @WebParam(name = "zlecenie", targetNamespace = "")
        ZleceniePrzelewuMiedzynarodowego zlecenie);

    /**
     * 
     * @param status
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/inicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego")
    @Oneway
    @RequestWrapper(localName = "inicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/", className = "pw.ee.mgr.ebanking.operacjebankowe.InicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego")
    public void inicjujZakonczenieProcesowaniaPrzelewuMiedzynarodowego(
        @WebParam(name = "status", targetNamespace = "")
        StatusZleceniaPrzelewu status);

    /**
     * 
     * @param kwota
     * @param nrKonta
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/wplacPieniadzeNaKonto")
    @Oneway
    @RequestWrapper(localName = "wplacPieniadzeNaKonto", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/", className = "pw.ee.mgr.ebanking.operacjebankowe.WplacPieniadzeNaKonto")
    public void wplacPieniadzeNaKonto(
        @WebParam(name = "nrKonta", targetNamespace = "")
        String nrKonta,
        @WebParam(name = "kwota", targetNamespace = "")
        double kwota);

    /**
     * 
     * @param kwota
     * @param nrKonta
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/wyplacPieniadzeZKonta")
    @Oneway
    @RequestWrapper(localName = "wyplacPieniadzeZKonta", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieOperacjamiBankowymi/", className = "pw.ee.mgr.ebanking.operacjebankowe.WyplacPieniadzeZKonta")
    public void wyplacPieniadzeZKonta(
        @WebParam(name = "kwota", targetNamespace = "")
        double kwota,
        @WebParam(name = "nrKonta", targetNamespace = "")
        String nrKonta);

}
