//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://Main/ServicesIdentification/ZarzadzanieRozliczeniami/")
package pw.ee.mgr.ebanking.rozliczenia;
