//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.rozliczenia;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

@WebService(name = "ZarzadzanieRozliczeniami", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieRozliczeniami/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZarzadzanieRozliczeniami {


    /**
     * 
     * @param zlecenie
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ZarzadzanieRozliczeniami/inicjujRejestracjeKwotyPrzelewuMiedzynarodowegoWSystemieRozliczen")
    @Oneway
    @RequestWrapper(localName = "inicjujRejestracjeKwotyPrzelewuMiedzynarodowegoWSystemieRozliczen", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieRozliczeniami/", className = "pw.ee.mgr.ebanking.rozliczenia.InicjujRejestracjeKwotyPrzelewuMiedzynarodowegoWSystemieRozliczen")
    public void inicjujRejestracjeKwotyPrzelewuMiedzynarodowegoWSystemieRozliczen(
        @WebParam(name = "zlecenie", targetNamespace = "")
        ZleceniePrzelewuMiedzynarodowego zlecenie);

    /**
     * 
     * @param zlecenie
     */
    @WebMethod(action = "http://Main/ServicesIdentification/ZarzadzanieRozliczeniami/zlecRejestracjeKwotyPrzelewuMiedzynarodowegoWSystemieRozliczen")
    @Oneway
    @RequestWrapper(localName = "zlecRejestracjeKwotyPrzelewuMiedzynarodowegoWSystemieRozliczen", targetNamespace = "http://Main/ServicesIdentification/ZarzadzanieRozliczeniami/", className = "pw.ee.mgr.ebanking.rozliczenia.ZlecRejestracjeKwotyPrzelewuMiedzynarodowegoWSystemieRozliczen")
    public void zlecRejestracjeKwotyPrzelewuMiedzynarodowegoWSystemieRozliczen(
        @WebParam(name = "zlecenie", targetNamespace = "")
        ZleceniePrzelewuMiedzynarodowego zlecenie);

}
