//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package pw.ee.mgr.ebanking.weryfikator;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "KontrolaPrzeplywowFinansowych", targetNamespace = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KontrolaPrzeplywowFinansowych {


    /**
     * 
     * @param zlecenie
     */
    @WebMethod(action = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/inicjujWykonaniePrzelewu")
    @Oneway
    @RequestWrapper(localName = "inicjujWykonaniePrzelewu", targetNamespace = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/", className = "pw.ee.mgr.ebanking.weryfikator.InicjujWykonaniePrzelewu")
    public void inicjujWykonaniePrzelewu(
        @WebParam(name = "zlecenie", targetNamespace = "")
        ZleceniePrzelewuMiedzynarodowego zlecenie);

    /**
     * 
     * @param zlecenie
     * @return
     *     returns pw.ee.mgr.ebanking.weryfikator.WynikWeryfikacjiMozliwosciWykonaniaPrzelewuMiedzynarodowego
     */
    @WebMethod(action = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/weryfikacjaMozliwosciWykonaniaPrzelewuMiedzynarodowego")
    @WebResult(name = "weryfikacjaMozliwosciWykonaniaPrzelewuMiedzynarodowego", targetNamespace = "")
    @RequestWrapper(localName = "weryfikacjaMozliwosciWykonaniaPrzelewuMiedzynarodowego", targetNamespace = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/", className = "pw.ee.mgr.ebanking.weryfikator.WeryfikacjaMozliwosciWykonaniaPrzelewuMiedzynarodowego")
    @ResponseWrapper(localName = "weryfikacjaMozliwosciWykonaniaPrzelewuMiedzynarodowegoResponse", targetNamespace = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/", className = "pw.ee.mgr.ebanking.weryfikator.WeryfikacjaMozliwosciWykonaniaPrzelewuMiedzynarodowegoResponse")
    public WynikWeryfikacjiMozliwosciWykonaniaPrzelewuMiedzynarodowego weryfikacjaMozliwosciWykonaniaPrzelewuMiedzynarodowego(
        @WebParam(name = "zlecenie", targetNamespace = "")
        ZleceniePrzelewuMiedzynarodowego zlecenie);

    /**
     * 
     * @param zlecenie
     * @return
     *     returns pw.ee.mgr.ebanking.weryfikator.WynikWeryfikacjiZleceniaPrzelewu
     */
    @WebMethod(action = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/weryfikujZleceniePrzelewuMiedzynarodowego")
    @WebResult(name = "wynikWeryfikacjiZleceniaPrzelewu", targetNamespace = "")
    @RequestWrapper(localName = "weryfikujZleceniePrzelewuMiedzynarodowego", targetNamespace = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/", className = "pw.ee.mgr.ebanking.weryfikator.WeryfikujZleceniePrzelewuMiedzynarodowego")
    @ResponseWrapper(localName = "weryfikujZleceniePrzelewuMiedzynarodowegoResponse", targetNamespace = "http://Main/ServicesIdentification/KontrolaPrzeplywowFinansowych/", className = "pw.ee.mgr.ebanking.weryfikator.WeryfikujZleceniePrzelewuMiedzynarodowegoResponse")
    public WynikWeryfikacjiZleceniaPrzelewu weryfikujZleceniePrzelewuMiedzynarodowego(
        @WebParam(name = "zlecenie", targetNamespace = "")
        ZleceniePrzelewuMiedzynarodowego zlecenie);

}
